spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /

server:
  port: 8888
  servlet:
    context-path: /chenhao

jdbc:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/d_msg?serverTimezone=GMT%2B8
    user: root
    password: 123456

